#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// This crate serves as an ESP-IDF component for Ableton Link.
// The actual bindings are generated by esp-idf-sys and available at:
// esp_idf_svc::sys::link::*
//
// This is just a marker crate to organize the component files.
